### PR TITLE
Fix storefront not running on platform with 3.0+

### PR DESCRIPTION
**Pull request by tomaszszymanski129**
as in title

### CODE REVIEW

**Comment by tasawar-hussain** [comment]
@tomaszszymanski129 , still unable to run the storefront. The port 3000 is not bound , any other configuration which needs to be done. Below are my tags for all repos.

Saleor: 3.1.0-a.5
Saleor-dashboard: 3.1.0-a.4
Saleor-storefront: 3.0.0-b.2

**Comment by tomaszszymanski129** [comment]
@tasawar-hussain the changed network mode should expose it without issues, the main problem was hitting the backend but with new driver that's also sorted out. Dockerfiles in storefront were modified but it's mot merged yet, could you try rebuilding it?:
- checkout storefront to branch `fix-dockerfiles`
- run `docker-compose build saleor-storefront`
- run `docker-compose up saleor-storefront`

**Comment by tasawar-hussain** [comment]
> @tasawar-hussain the changed network mode should expose it without issues, the main problem was hitting the backend but with new driver that's also sorted out. Dockerfiles in storefront were modified but it's mot merged yet, could you try rebuilding it?:
> 
> * checkout storefront to branch `fix-dockerfiles`
> * run `docker-compose build saleor-storefront`
> * run `docker-compose up saleor-storefront`

No luck , still localhost refused to connect for storefront

**Review by maarcingebala — APPROVED** [review]

**Comment by tanoabeleyra** [comment]
This is not working for me either, I can not hit the storefront. Instead, with the previous configuration it works fine.
What was the reason for this change?

**Pull request merged**
